In [36]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [37]:
data = "col_trans.xlsx"
df = pd.read_excel(data)
df.head()

  Social Media          Review  age  Sentiment
0      Twitter            Good   21          1
1     Facebook    Too many ads   19          0
2        Insta  Great for post  NAN          0
3      Twitter       Fantastic   39          1

In [45]:
column_transformer = ColumnTransformer(
    transformers=[
        ('text', CountVectorizer(),'Review' ),
        ('social', OneHotEncoder(), ['Social Media']),
        ('num', SimpleImputer(strategy='mean'), ['age'])
    ],
    remainder='drop'
)

In [47]:
transformed = column_transformer.fit_transform(df)
pd.DataFrame(transformed,columns=column_transformer.get_feature_names_out())

,text__ads,text__fantastic,text__for,text__good,text__great,text__many,text__post,text__too,social__Social Media_Facebook,social__Social Media_Insta,social__Social Media_Twitter,num__age
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,21.000000
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,19.000000
2,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,26.333333
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,39.000000