In [14]:
import numpy as np
import pandas as pd
from sklearn.pipeline import FeatureUnion
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [23]:
np.random.seed(42)
data = np.random.randn(10,4)
df = pd.DataFrame(data,columns=['c1','c2','c3','y'])
df

         c1        c2        c3         y
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730
3  0.241962 -1.913280 -1.724918 -0.562288
4 -1.012831  0.314247 -0.908024 -1.412304
5  1.465649 -0.225776  0.067528 -1.424748
6 -0.544383  0.110923 -1.150994  0.375698
7 -0.600639 -0.291694 -0.601707  1.852278
8 -0.013497 -1.057711  0.822545 -1.220844
9  0.208864 -1.959670 -1.328186  0.196861

In [24]:
feature = FeatureUnion([
    ("scaler", StandardScaler()),
    ("pca", PCA(n_components=2))
])

In [25]:
transformed = feature.fit_transform(df.drop(columns=['y']))
pd.DataFrame(transformed,columns=feature.get_feature_names_out())

   scaler__c1  scaler__c2  scaler__c3  pca__pca0  pca__pca1
0    0.815293    0.418360    0.947878   1.025659  -0.425413
1   -0.282292    0.302777    1.873701   1.772532  -0.358223
2   -0.635686    1.239158   -0.156427   0.327888   1.038742
3    0.432718   -1.721587   -1.410206  -1.911072  -0.689960
4   -1.451676    0.963905   -0.598312  -0.193153   1.371662
5    2.270396    0.312856    0.371269   0.511760  -0.891133
6   -0.748180    0.718778   -0.839795  -0.484280   1.020731
7   -0.832663    0.233387   -0.293870  -0.191723   0.583958
8    0.049080   -0.690119    1.121664   0.726878  -0.811461
9    0.383011   -1.777515   -1.015903  -1.584488  -0.838903