In [20]:
from sklearn.pipeline import Pipeline
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression

In [13]:
np.random.seed(42)
data = np.random.randn(10,4)
df = pd.DataFrame(data,columns=['c1','c2','c3','y'])
df

         c1        c2        c3         y
0  0.496714 -0.138264  0.647689  1.523030
1 -0.234153 -0.234137  1.579213  0.767435
2 -0.469474  0.542560 -0.463418 -0.465730
3  0.241962 -1.913280 -1.724918 -0.562288
4 -1.012831  0.314247 -0.908024 -1.412304
5  1.465649 -0.225776  0.067528 -1.424748
6 -0.544383  0.110923 -1.150994  0.375698
7 -0.600639 -0.291694 -0.601707  1.852278
8 -0.013497 -1.057711  0.822545 -1.220844
9  0.208864 -1.959670 -1.328186  0.196861

In [21]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=2)),
    ('regression', LinearRegression())])

In [28]:
X = df[['c1', 'c2', 'c3']]
X_transformed = pipeline[:-1].transform(X)

pd.DataFrame(
    X_transformed,
    columns=pipeline[:-1].get_feature_names_out()
)

       pca0      pca1
0  0.259406  1.275005
1  1.074645  1.255828
2  1.227399 -0.450157
3 -2.079220 -0.900035
4  1.267134 -1.332941
5 -0.780321  1.776439
6  0.627837 -1.074993
7  0.497471 -0.748148
8 -0.143582  0.836302
9 -1.950769 -0.637301